repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local # local hooks
    hooks:
    -   id: swag
        name: swag
        entry: swag init # system command
        language: system # use system command 
        pass_filenames: false # no filenames will be passed to swag hook
        files: \.go$ # run only on go files
        description: Generate Swagger REST API documents
