definitions:
  view.CreateEmployeeRequest:
    properties:
      age:
        type: integer
      name:
        type: string
      title:
        description: |-
          Employee title:
          * engineer - developer, programer.
          * manager - product manger, project manager, supervisor.
        enum:
        - engineer
        - manager
        type: string
    type: object
  view.CreateEmployeeResponse:
    properties:
      createdAt:
        type: string
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: 菜鳥工程師肉豬
    url: https://matthung0807.blogspot.com/
  description: Swagger API.
  title: Swagger Demo
  version: "1.0"
paths:
  /employee:
    post:
      description: Create a new employee
      parameters:
      - description: create params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/view.CreateEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.CreateEmployeeResponse'
      summary: Create a new employee
      tags:
      - employee
  /hello:
    get:
      parameters:
      - description: user name
        in: query
        name: name
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      tags:
      - Hello
swagger: "2.0"
