host: localhost:8080
info:
  contact: {}
  description: Swagger REST API.
  title: Swagger Demo
  version: "1.0"
paths:
  /demo/hello:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
swagger: "2.0"
